### ISSUE TITLE
Fix batch buildpsec entry

### ISSUE THREAD

**Issue by tomuben** [exasol/script-languages-container-ci-setup#22]
## Background

The batch build spec entry per flavor looks currently like:
```
 - identifier: build_python_36_data_science_cuda_EXASOL_620
      env:
        variables:
          FLAVOR: python-3.6-data-science-cuda-EXASOL-6.2.0
      buildspec: ./aws-code-build/ci/build_buildspec.yaml
      privileged-mode: true
      type: BUILD_GENERAL1_LARGE
```

However, according to the [AWS documentation](https://docs.aws.amazon.com/codebuild/latest/userguide/batch-build-buildspec.html) The entry `privileged-mode` must be part of `env`. Also, `type` must be under `env`, but using key `computeType`.
